django-homeinv/app_homeinv/urls.py
from django.urls import path

from . import views

app_name = 'app_homeinv'

urlpatterns = [
    # Group
    path('groups', views.GroupListView.as_view(), name='group-list'),
    path('group/create', views.GroupCreateView.as_view(), name='group-create'),
    path('group/<pk>', views.GroupDetailView.as_view(), name='group-detail'),
    path('group/<pk>/update', views.GroupUpdateView.as_view(), name='group-update'),
    path('group/<pk>/delete', views.GroupDeleteView.as_view(), name='group-delete'),

    # Item
    path('items', views.ItemListView.as_view(), name='item-list'),
    path('item/create', views.ItemCreateView.as_view(), name='item-create'),
    path('item/<pk>', views.ItemDetailView.as_view(), name='item-detail'),
    path('item/<pk>/update', views.ItemUpdateView.as_view(), name='item-update'),
    path('item/<pk>/delete', views.ItemDeleteView.as_view(), name='item-delete'),
    path('item/<pk>/create-placed/', views.ItemPlacedCreateView.as_view(), name='item-placed-create'),

    # Item-Placed
    path('item-placed/<pk>/update', views.ItemPlacedUpdateView.as_view(), name='item-placed-update'),
    path('item-placed/<pk>/delete', views.ItemPlacedDeleteView.as_view(), name='item-placed-delete'),
]

django-homeinv/homeinv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('inv/', include('app_homeinv.urls', 'homeinv')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

django-homeinv/app_homeinv/models.py
import json

from django.db import models
from django.urls import reverse_lazy


class Group(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    photo = models.ImageField(upload_to='groups')

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse_lazy('homeinv:group-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    photo = models.ImageField(upload_to='items')
    groups = models.ManyToManyField(Group)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse_lazy('homeinv:item-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class ItemPlaced(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    description = models.TextField()
    count = models.IntegerField(default=0)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return self.item.get_absolute_url()

django-homeinv/app_homeinv/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.detail import SingleObjectTemplateResponseMixin
from django import forms
from django.urls import reverse_lazy

from . import models


# Group views

class GroupCreateView(generic.CreateView):
    model = models.Group
    fields = ['name', 'description', 'photo']


class GroupDetailView(generic.DetailView):
    model = models.Group


class GroupUpdateView(generic.UpdateView):
    model = models.Group
    fields = ['name', 'description', 'photo']


class GroupDeleteView(generic.DeleteView):
    model = models.Group
    success_url = reverse_lazy('index')


class GroupListView(generic.ListView):
    model = models.Group


# Item views

class ItemCreateView(generic.CreateView):
    model = models.Item
    fields = ['name', 'description', 'photo', 'groups']


class ItemDetailView(generic.DetailView):
    model = models.Item


class ItemUpdateView(generic.UpdateView):
    model = models.Item
    fields = ['name', 'description', 'photo', 'groups']


class ItemDeleteView(generic.DeleteView):
    model = models.Item
    success_url = reverse_lazy('index')


class ItemListView(generic.ListView):
    model = models.Item


class ParentMixin():
    def get_success_url(self):
        return getattr(self.object, self.parent_field).get_absolute_url()


class ParentCreateView(
    ParentMixin,
    SingleObjectTemplateResponseMixin,
    generic.edit.BaseCreateView
):
    parent_field = None

    template_name_suffix = '_form'

    def get_initial(self):
        return {
            self.parent_field: self.kwargs['pk']
        }

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields[self.parent_field].widget = forms.HiddenInput()
        return form


class ItemPlacedCreateView(ParentCreateView):
    template_name = 'form.html'
    model = models.ItemPlaced
    parent_field = 'item'
    fields = ['item', 'description', 'count']


class ItemPlacedUpdateView(generic.UpdateView):
    template_name = 'form.html'
    model = models.ItemPlaced
    fields = ['item', 'description', 'count']


class ItemPlacedDeleteView(generic.DeleteView):
    template_name = 'confirm_delete.html'
    model = models.ItemPlaced
    fields = ['item', 'description', 'count']
    
    def get_success_url(self):
        return self.object.item.get_absolute_url()

django-homeinv/app_homeinv/templates/app_homeinv/group_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1 class="display-4">Delete "{{ object.name }}" group</h1>
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object.name }}" group?</p>
    <input class="btn btn-danger" type="submit" value="Confirm" />
  </form>
</div>
{% endblock content %}

django-homeinv/app_homeinv/templates/app_homeinv/group_detail.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
  <div class="container">
    <div class="media">
      <img class="rounded shadow mr-3" src="{{ object.photo.url }}" style="max-width: 20vw;"/>
      <div class="media-body">
        <h1 class="display-4">{{ object.name }}</h1>
        <p>{{ object.description }}</p>
        <a class="btn btn-secondary" href="{% url 'homeinv:group-update' object.pk %}">Edit</a>
        <a class="btn btn-danger" href="{% url 'homeinv:group-delete' object.pk %}">Delete</a>
      </div>
    </div>
  </div>
</div>

<div class="container">
  {% include "app_homeinv/includes/items_list.html" with items=object.item_set.all only %}
</div>
{% endblock content %}

django-homeinv/app_homeinv/templates/app_homeinv/group_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <h1 class="display-4">Group form</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit">
  </form>
</div>
{% endblock content %}

django-homeinv/app_homeinv/templates/app_homeinv/group_list.html
{% extends "base.html" %}

{% block content %}
<style>
  .my-thumb {
    width: 5em;
    height: 5em;
    object-fit: cover;
  }

  .my-item {
    display: flex;
  }

  .my-hspace {
    width: 1em;
  }
</style>

<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">Group list</h1>
    <a class="btn btn-primary btn-lg" href="{% url 'homeinv:group-create' %}">Add group</a>
  </div>
</div>

<div class="container">
  <div class="list-group">
    {% for group in object_list %}
      <a href="{% url 'homeinv:group-detail' group.pk %}" class="my-item list-group-item list-group-item-action">
        <img class="my-thumb rounded" src="{{ group.photo.url }}" alt="{{ group.name }} photo">
        <div class="my-hspace"></div>
        <div class="w-100">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ group.name }}</h5>
            <small>{{ group.created }}</small>
          </div>
          <p>
            {{ group.description }}
          </p>
        </div>
      </a>
    {% endfor %}
    </div>

</div>
{% endblock content %}

django-homeinv/app_homeinv/templates/app_homeinv/includes/items_list.html
<style>
  .my-thumb {
    width: 5em;
    height: 5em;
    object-fit: cover;
  }

  .my-item {
    display: flex;
  }

  .my-hspace {
    width: 1em;
  }
</style>

<div class="list-group">
  {% for item in items %}
    <a href="{% url 'homeinv:item-detail' item.pk %}" class="my-item list-group-item list-group-item-action">
      <img class="my-thumb rounded" src="{{ item.photo.url }}" alt="{{ item.name }} photo">
      <div class="my-hspace"></div>
      <div class="w-100">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{ item.name }}</h5>
          <small>{{ item.created }}</small>
        </div>
        <p>
          {{ item.description }}
        </p>
      </div>
    </a>
  {% endfor %}
</div>

django-homeinv/app_homeinv/templates/app_homeinv/item_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1 class="display-4">Delete "{{ object.name }}"</h1>
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object.name }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm" />
  </form>
</div>
{% endblock content %}

django-homeinv/app_homeinv/templates/app_homeinv/item_detail.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
  <div class="container">
    <div class="media">
      <img class="rounded shadow mr-3" src="{{ object.photo.url }}" style="max-width: 20vw;"/>
      <div class="media-body">
        <h1 class="h5">{{ object.name }}</h1>
        <p>{{ object.description }}</p>
        <div>
          <strong> Groups: </strong>
          {% for group in object.groups.all %}
            <a href="{{ group.get_absolute_url }}">{{ group }}</a>
          {% endfor %}
        </div>
        <a class="btn btn-primary" href="{% url 'homeinv:item-placed-create' object.pk %}">Add placement</a>
        <a class="btn btn-secondary" href="{% url 'homeinv:item-update' object.pk %}">Edit</a>
        <a class="btn btn-danger" href="{% url 'homeinv:item-delete' object.pk %}">Delete</a>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div>
    {% for itemplaced in object.itemplaced_set.all %}
      <div>
        {{ itemplaced.description }} - {{ itemplaced.count }}
        <a href="{% url 'homeinv:item-placed-update' itemplaced.pk %}">Edit</a>
        <a href="{% url 'homeinv:item-placed-delete' itemplaced.pk %}">Delete</a>
      </div>
    {% endfor %}
  </div>
</div>

{% endblock content %}

django-homeinv/app_homeinv/templates/app_homeinv/item_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <h1 class="display-4">Item form</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit">
  </form>
</div>
{% endblock content %}

django-homeinv/app_homeinv/templates/app_homeinv/item_list.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">Item list</h1>
    <a class="btn btn-primary btn-lg" href="{% url 'homeinv:item-create' %}">Add item</a>
  </div>
</div>

<div class="container">
  {% include "app_homeinv/includes/items_list.html" with items=object_list only %}
</div>

</div>
{% endblock content %}

django-homeinv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>HomeInv</title>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container">
      <a href="/" class="navbar-brand">HomeInv</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="navbar-item">
            <a href="{% url 'homeinv:group-list' %}" class="nav-link">Groups</a>
          </li>
          <li class="navbar-item">
            <a href="{% url 'homeinv:item-list' %}" class="nav-link">Items</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}
  {% endblock content %}
</body>
</html>

django-homeinv/templates/confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1 class="display-4">Delete "{{ object }}"</h1>
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm" />
  </form>
</div>
{% endblock content %}

django-homeinv/templates/form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <h1 class="display-4">Form</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Save">
  </form>
</div>
{% endblock content %}

django-homeinv/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1 class="display-4">Index page</h1>

  <a href="{% url 'homeinv:item-create' %}"> Add item </a>
</div>
{% endblock content %}